# Generated by Django 4.1.5 on 2023-01-14 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("dataSheet", models.FileField(blank=True, null=True, upload_to="")),
                ("CVrate", models.FloatField(blank=True, null=True)),
                ("kNeighbors", models.PositiveIntegerField(blank=True, null=True)),
                ("metric", models.CharField(blank=True, max_length=50, null=True)),
                ("isKNN", models.BooleanField(default=False)),
                ("isDT", models.BooleanField(default=False)),
                ("isNB", models.BooleanField(default=False)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("createdTime", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["accuracy"],
            },
        ),
    ]
